---
title: "131projectfile"
output: html_document
---

```{r, echo=FALSE}
library(spotifyr)
library(tidyverse)
library(knitr)
library(lubridate)
library(httpuv)
```

```{r}
music <- read.csv("https://github.com/abauer726/DoubleProjectGroup/blob/main/131%20Project/Spotify%20Dataset/musicdata.csv")
View(music)


# New research question: can we predict if a song will be a hit based on its attributes? Response variable: song.hotttnesss 

# anna path name music: /Users/kimbauer/Desktop/DoubleProjectGroup/131 Project/Spotify Dataset/musicdata.csv
# anna path name music w genre: /Users/kimbauer/Desktop/DoubleProjectGroup/131 Project/Spotify Dataset/data_w_genres.csv


# grant path name music: /Users/Grant/DoubleProjectGroup/131 Project/Spotify Dataset/musicdata.csv
# grant path name music w genre: /Users/Grant/DoubleProjectGroup/131 Project/Spotify Dataset/data_w_genres.csv

# lex path name music: /Users/lexnavarra/Desktop/DoubleProjectGroup/131 Project/Spotify Dataset/musicdata.csv
# lex path name music w genre: /Users/lexnavarra/Desktop/DoubleProjectGroup/131 Project/Spotify Dataset/data_w_genres.csv
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=T}
energy <- ggplot(music,aes(x=energy,y=popularity))+geom_point()
energy

liveness <- ggplot(music,aes(x=liveness, y=popularity))+geom_point()
liveness
```


```{r}
valence <- ggplot(music, aes(x=valence, y=popularity))+geom_point(alpha=0.2) + facet_grid(vars(danceability))
valence
```

```{r}
# randomly subset syntax, with 100 points (couldnt run this due to the file not loading)

music[sample(nrow(music), 100), ]
```


